In [136]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import svm
from sklearn import metrics
from sklearn import naive_bayes
from sklearn.metrics import f1_score

In [127]:
data = [
    "how are this",
    "how are you",
    "how are you doing",
    "what is your name",
    "tell me about yourself",
    "yet another question",
    "what is your age",
    "last question",
    "please answer me",
    "key word",
    "one more question",
    "for the last time",
    "please please answer me",
    "you look good",
    "you look great",
    "this project is great"
]

In [78]:
# read the data from the csv file dataset/train.csv
file_data = pd.read_csv("./Dataset/Dataset/train.csv")

In [79]:
data = file_data['text'].values

In [128]:
vectorizer = None
vectorizer = CountVectorizer(token_pattern=r'\S+')
vectorizer.fit_transform(data)

<16x31 sparse matrix of type '<class 'numpy.int64'>'
	with 52 stored elements in Compressed Sparse Row format>

In [81]:
#print(vectorizer.vocabulary_)

In [137]:
TF_IDF = None
from sklearn.feature_extraction.text import TfidfVectorizer
TF_IDF = TfidfVectorizer(token_pattern=r'\S+')
TF_IDF.fit_transform(data)

<16x31 sparse matrix of type '<class 'numpy.float64'>'
	with 52 stored elements in Compressed Sparse Row format>

In [138]:
bag_of_words = vectorizer.transform(data)
tf_idf = TF_IDF.transform(data)

In [134]:
print(bag_of_words.toarray())
print(len(bag_of_words.toarray()[0]))

[[0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 0

In [139]:
print(tf_idf.toarray())
print(len(tf_idf.toarray()[0]))

[[0.         0.         0.         0.         0.55478891 0.
  0.         0.         0.         0.55478891 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.62001494
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.59486632 0.
  0.         0.         0.         0.59486632 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.54061827 0.
  0.        ]
 [0.         0.         0.         0.         0.47283995 0.60678295
  0.         0.         0.         0.47283995 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.42971993 0.
  0.        ]
 [0.         0.         0.         0.     

In [131]:
test_data = [
    "how are you",
    "what is your name",
    "do you know me",
    "your work is so good",
    "you look great",
    "this project failed"
]


In [85]:
test_data_file = pd.read_csv("./Dataset/Dataset/dev.csv")

In [86]:
test_data = test_data_file['text'].values

In [87]:
# remove any word in test not in vectorizer vocabulary
#test_data_preprocessed = [' '.join([word for word in sentence.split() if word in vectorizer.vocabulary_]) for sentence in test_data]

In [140]:
test_bag_of_words = vectorizer.transform(test_data)

In [141]:
test_tf_idf = TF_IDF.transform(test_data)

In [142]:
print(test_bag_of_words.toarray())
print(len(test_bag_of_words.toarray()[0]))

[[0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0]]
31


In [143]:
print(test_tf_idf.toarray())
print(len(test_tf_idf.toarray()[0]))

[[0.         0.         0.         0.         0.59486632 0.
  0.         0.         0.         0.59486632 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.54061827 0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.44087905 0.
  0.         0.         0.         0.         0.56576838 0.
  0.         0.         0.         0.         0.         0.
  0.         0.4927128  0.         0.         0.         0.4927128
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.74004489 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.67255747 0.
  0.        ]
 [0.         0.         0.         0.         0.   

In [90]:
# svm
# concatenate the two features
#bag_of_words = bag_of_words.toarray()
clf = svm.SVC()
clf.fit(bag_of_words, file_data['stance'].values)


SVC()

In [91]:
predited = clf.predict(test_bag_of_words)

In [92]:
actual = test_data_file['stance'].values

In [93]:
# f1 score

stance_f1 = f1_score(actual, predited, average='macro')
print(stance_f1)

0.38719891628832004


In [94]:
# another classifier for category
clf2 = svm.SVC()
clf2.fit(bag_of_words, file_data['category'].values)

SVC()

In [95]:
predited2 = clf2.predict(test_bag_of_words)

In [96]:
actual2 = test_data_file['category'].values

In [97]:
category_f1 = f1_score(actual2, predited2, average='macro')
print(category_f1)

0.23648439875233446


In [98]:
# macro f1 score for both
macro_f1 = (stance_f1 + category_f1) / 2

In [99]:
print(macro_f1)

0.3118416575203272


In [101]:
nb = naive_bayes.MultinomialNB()

In [102]:
nb.fit(bag_of_words, file_data['stance'].values)

MultinomialNB()

In [103]:
nb_predited = nb.predict(test_bag_of_words)

In [112]:
nb_stance_f1 = f1_score(actual, nb_predited, average='macro')
print(nb_stance_f1)

0.41022801278825377


In [105]:
nb2 = naive_bayes.MultinomialNB()

In [106]:
nb2.fit(bag_of_words, file_data['category'].values)

MultinomialNB()

In [107]:
nb2_predited = nb2.predict(test_bag_of_words)

In [111]:
nb_category_f1 = f1_score(actual2, nb2_predited, average='macro')
print(nb_category_f1)

0.2505719059915458


In [109]:
# macro f1 score for both
nb_macro_f1 = (nb_stance_f1 + nb_category_f1) / 2

In [113]:
print(nb_macro_f1)

0.33039995938989974


In [115]:
# use sklearn metrics to get the confusion matrix
print(metrics.classification_report(actual, predited))

              precision    recall  f1-score   support

          -1       0.56      0.07      0.13        70
           0       0.50      0.08      0.14       126
           1       0.82      0.99      0.90       804

    accuracy                           0.81      1000
   macro avg       0.63      0.38      0.39      1000
weighted avg       0.76      0.81      0.75      1000



In [116]:
print(metrics.classification_report(actual2, predited2))

              precision    recall  f1-score   support

      advice       0.00      0.00      0.00        10
   celebrity       0.87      0.71      0.78       145
   info_news       0.65      0.95      0.77       545
      others       0.00      0.00      0.00        17
    personal       0.68      0.36      0.47       128
        plan       1.00      0.01      0.02        82
    requests       1.00      0.05      0.10        20
restrictions       0.00      0.00      0.00         2
      rumors       0.00      0.00      0.00        15
   unrelated       0.62      0.14      0.23        36

    accuracy                           0.67      1000
   macro avg       0.48      0.22      0.24      1000
weighted avg       0.69      0.67      0.60      1000



c:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [117]:
print(metrics.classification_report(actual, nb_predited))

              precision    recall  f1-score   support

          -1       0.75      0.04      0.08        70
           0       0.53      0.17      0.25       126
           1       0.83      0.98      0.90       804

    accuracy                           0.81      1000
   macro avg       0.70      0.40      0.41      1000
weighted avg       0.78      0.81      0.76      1000



In [118]:
print(metrics.classification_report(actual2, nb2_predited))

              precision    recall  f1-score   support

      advice       0.00      0.00      0.00        10
   celebrity       0.92      0.77      0.83       145
   info_news       0.68      0.94      0.79       545
      others       0.00      0.00      0.00        17
    personal       0.59      0.49      0.54       128
        plan       0.00      0.00      0.00        82
    requests       0.00      0.00      0.00        20
restrictions       0.00      0.00      0.00         2
      rumors       0.00      0.00      0.00        15
   unrelated       0.80      0.22      0.35        36

    accuracy                           0.70      1000
   macro avg       0.30      0.24      0.25      1000
weighted avg       0.61      0.70      0.63      1000



c:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Python39\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [120]:
# implement TF-IDF
data = [
    "how are this",
    "how are you",
    "how are you doing",
    "what is your name",
    "tell me about yourself",
    "yet another question",
    "what is your age",
    "last question",
    "please answer me",
    "key word",
    "one more question",
    "for the last time",
    "please please answer me",
    "you look good",
    "you look great",
    "this project is great"
]


In [121]:
TF_IDF = None
from sklearn.feature_extraction.text import TfidfVectorizer
TF_IDF = TfidfVectorizer(token_pattern=r'\S+')
TF_IDF.fit_transform(data)

tf_idf_bag_of_words = TF_IDF.transform(data)

In [122]:
print(tf_idf_bag_of_words.toarray())

[[0.         0.         0.         0.         0.55478891 0.
  0.         0.         0.         0.55478891 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.62001494
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.59486632 0.
  0.         0.         0.         0.59486632 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.54061827 0.
  0.        ]
 [0.         0.         0.         0.         0.47283995 0.60678295
  0.         0.         0.         0.47283995 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.42971993 0.
  0.        ]
 [0.         0.         0.         0.     

In [123]:
test_data = [
    "how are you",
    "what is your name",
    "do you know me",
    "your work is so good",
    "you look great",
    "this project failed"
]
    

In [124]:
test_tf_idf_bag_of_words = TF_IDF.transform(test_data)

In [125]:
print(test_tf_idf_bag_of_words.toarray())

[[0.         0.         0.         0.         0.59486632 0.
  0.         0.         0.         0.59486632 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.54061827 0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.44087905 0.
  0.         0.         0.         0.         0.56576838 0.
  0.         0.         0.         0.         0.         0.
  0.         0.4927128  0.         0.         0.         0.4927128
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.74004489 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.67255747 0.
  0.        ]
 [0.         0.         0.         0.         0.   